[project]
name = "limitless-api-order-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eth-account==0.10.0",
    "python-dotenv>=0.9.9",
    "requests>=2.32.5",
    "web3>=6.20.4",
]
